require 'csv'

Book.destroy_all
Author.destroy_all
User.destroy_all

books = [nil]

lines = CSV.new(File.open('./db/book-seeds.csv'), headers: true, header_converters: :symbol).read
lines.each do |line|
  line = line.to_h
  line[:authors] = [Author.find_or_create_by!(name: line[:author])]
  line.delete(:author)
  books << Book.create!(line)
end

user_1 = User.create(name: "Ilovereading")
user_2 = User.create(name: "Tomas 1999")
user_3 = User.create(name: "Diego Marco")
user_4 = User.create(name: "Joaquin meteme")
user_5 = User.create(name: "Inma Oteros")
user_6 = User.create(name: "De Marco Perez")
user_7 = User.create(name: "Noone")
user_8 = User.create(name: "Is Peter Okay")
user_9 = User.create(name: "Zach loves pickles")
user_10 = User.create(name: "Trevor the hugger")
user_11 = User.create(name: "Tim says sorry")
user_12 = User.create(name: "Chris dimples")
user_13 = User.create(name: "Fit Jennica")
user_14 = User.create(name: "Tall Tere")
user_15 = User.create(name: "Earl Snoopy")
user_16 = User.create(name: "Scott x Kourtney")
user_17 = User.create(name: "Talking Ty")
user_18 = User.create(name: "Analitical April")
user_19 = User.create(name: "Vince not Vinny")
user_20 = User.create(name: "Pippin")
user_21 = User.create(name: "Noah and his hat")
user_22 = User.create(name: "Rene is not french")

books[1].reviews.create(rating: 2, title: "Not the best", review_text: "It was an average book", user_id: user_1.id)
books[1].reviews.create(rating: 4, title: "Loved it", review_text: "Enjoyed every single page of it!", user_id: user_2.id)
books[1].reviews.create(rating: 5, title: "Pretty awesome", review_text: "Interesting all the way until the end", user_id: user_3.id)
books[1].reviews.create(rating: 5, title: "Best book ever", review_text: "Could not stop reading it", user_id: user_4.id)
books[1].reviews.create(rating: 3, title: "Average book", review_text: "I though it would be better", user_id: user_7.id)
books[1].reviews.create(rating: 1, title: "Super Boring", review_text: "Do not waste your time reading this book", user_id: user_5.id)
books[2].reviews.create(rating: 2, title: "Not what I expected", review_text: "Definitely not worth it", user_id: user_6.id)
books[2].reviews.create(rating: 2, title: "Just ok", review_text: "It was kind of slow at some points in the book.", user_id: user_8.id)
books[2].reviews.create(rating: 3, title: "Overrated", review_text: "But still good. I read this a while ago", user_id: user_9.id)
books[2].reviews.create(rating: 1, title: "Lies, lies, lies and grandiosity.", review_text: "Don't fall for it", user_id: user_10.id)
books[2].reviews.create(rating: 5, title: "very well written", review_text: "I enjoyed reading this story and feel that we can all learn something from it.", user_id: user_11.id)
books[2].reviews.create(rating: 5, title: "Loved it!!", review_text: "So easy to read", user_id: user_12.id)
books[3].reviews.create(rating: 4, title: "Brillant & well written", review_text: "A fascinating & engaging read", user_id: user_13.id)
books[3].reviews.create(rating: 2, title: "Disappointed", review_text: "Read any book before this one", user_id: user_14.id)
books[3].reviews.create(rating: 2, title: "If you ever need some help sleeping this is the book for you", review_text: "I honestly have no idea what the critics were saying when they called this a great thriller with Grisham-like characters. This is NOT a good book.", user_id: user_15.id)
books[3].reviews.create(rating: 4, title: "Beyond inspiring", review_text: "The candor and compassion throughout this book delighted and inspired.", user_id: user_16.id)
books[3].reviews.create(rating: 2, title: "Dang, another", review_text: "The plot was great.... the story getting there not so much.", user_id: user_17.id)
books[3].reviews.create(rating: 3, title: "The title is misleading.", review_text: "The characters were very flat and the dialog as bad.", user_id: user_18.id)
books[4].reviews.create(rating: 4, title: "An amazing story", review_text: "Life, love, and family and a remarkable journey. A wonderful book.", user_id: user_19.id)
books[4].reviews.create(rating: 2, title: "Not his best", review_text: "The story is drawn out to the point I couldn't wait to be done.", user_id: user_20.id)
books[4].reviews.create(rating: 5, title: "Such a wonderful read!!", review_text: "Fell in love with the characters and the beautiful story", user_id: user_21.id)
books[4].reviews.create(rating: 5, title: "This book is everything I expected and more.", review_text: "I'm drawn in, the writing is captivating and emotional.", user_id: user_22.id)
books[4].reviews.create(rating: 1, title: "Too much too soon", review_text: "The story line is lame.", user_id: user_1.id)
books[4].reviews.create(rating: 3, title: "Beautiful edition", review_text: "The nicest English edition I've seen in a long time.", user_id: user_2.id)
books[4].reviews.create(rating: 2, title: "Be aware", review_text: "This is extremely hard to read. I was able to keep up with the plot through about the first half", user_id: user_3.id)
books[4].reviews.create(rating: 4, title: "A great read", review_text: "I thoroughly enjoyed every word of this beautifully crafted novel", user_id: user_4.id)
books[4].reviews.create(rating: 4, title: "A Story You Won't Forget...or Want To", review_text: "I read a lot and frankly there are books that fade from my memory within a week or two. This isn't one of those.", user_id: user_5.id)
books[4].reviews.create(rating: 3, title: "Nice summer read", review_text: "An easy read that is hard to put down.", user_id: user_6.id)
books[4].reviews.create(rating: 1, title: "Disappointing book by this author", review_text: "Somewhat simplistic and predictable.", user_id: user_7.id)
books[4].reviews.create(rating: 4, title: "Must read", review_text: "Beautifully written and creative", user_id: user_8.id)
books[5].reviews.create(rating: 1, title: "This is another formula book", review_text: "Next we'll have a co-writer and monthly new releases.", user_id: user_9.id)
books[5].reviews.create(rating: 1, title: "I love this author and always pre-order his books", review_text: "Not any more. Hard story to get into", user_id: user_10.id)
books[5].reviews.create(rating: 5, title: "One of my new favorites!", review_text: "Wow! Hard to believe this was a first time author.", user_id: user_11.id)
books[5].reviews.create(rating: 1, title: "The worst", review_text: "I bought this particular book with the expectation of being entertained as usual. Two chapters in I was asking who wrote this garbage?", user_id: user_12.id)
books[5].reviews.create(rating: 3, title: "Easy read", review_text: "A novel that pulls one in with anticipation for what happens next.", user_id: user_13.id)
books[5].reviews.create(rating: 2, title: "made the mistake of buying", review_text: "This is a book for youngsters.", user_id: user_14.id)
books[6].reviews.create(rating: 4, title: "Enjoyed it a lot", review_text: "Amazing story, hope it can never happen.", user_id: user_15.id)
books[6].reviews.create(rating: 2, title: "Bad ending", review_text: "This work just ended. It was like turning the page and done in the middle of a sentenance. Not what I expected.", user_id: user_16.id)
books[6].reviews.create(rating: 4, title: "Really good", review_text: "I enjoyed this one, good story line and an interesting main character. Sad but still inspirational. Good ending.", user_id: user_17.id)
books[6].reviews.create(rating: 1, title: "Unbelievable", review_text: "Ridiculous! Could have been written by a 5 year old!", user_id: user_18.id)
books[6].reviews.create(rating: 4, title: "Entertaining and fast-paced", review_text: "Great read, terrific characters", user_id: user_19.id)
books[6].reviews.create(rating: 5, title: "Great read", review_text: "A REALLY good story with lots of twists & turns!!!", user_id: user_20.id)
books[7].reviews.create(rating: 3, title: "Decent!", review_text: "Easy read and enjoyable!", user_id: user_21.id)
books[7].reviews.create(rating: 4, title: "A very different plot line", review_text: "A bright new lead character that will grab readers. Unique story line.", user_id: user_22.id)
books[7].reviews.create(rating: 1, title: "Who wrote this?", review_text: "Ridiculous, outlandish, absurd plot and a complete waste of time. Did not finish.", user_id: user_1.id)
books[7].reviews.create(rating: 2, title: "Horrible dialogue", review_text: "Cliche after stilted cliche, and cringe-worthy repartee between the lead characters, who have all the chemistry of a couple of claymation animals. There's not a single character with any depth to him.", user_id: user_2.id)
books[7].reviews.create(rating: 2, title: "Preposterous", review_text: "Absolutely silly and unbelievable", user_id: user_3.id)
books[7].reviews.create(rating: 5, title: "Great Read", review_text: "One book you hate to out down", user_id: user_4.id)
books[8].reviews.create(rating: 1, title: "The worst", review_text: "Worst book never read if you do you die", user_id: user_5.id)
books[8].reviews.create(rating: 3, title: "Nice read", review_text: "It starts out a little slow to begin with, but quickly becomes one you can hardly put down.", user_id: user_6.id)
books[8].reviews.create(rating: 5, title: "Just fantastic", review_text: "From the beginning to the end, non-stop excitement and surprise.", user_id: user_7.id)
books[8].reviews.create(rating: 4, title: "What a ride!!", review_text: "Fast paced action-filled as one would expect from this author. Was not disappointed, only that the book ended!", user_id: user_8.id)
books[8].reviews.create(rating: 3, title: "Lots of unexpected turns", review_text: "Lots of intrigue that builds to up to a very fast paced last half of the book. Delivers surprises yet they are not surprises after all.  ", user_id: user_9.id)
books[8].reviews.create(rating: 5, title: "Another excellent read from an outstanding author", review_text: "Just reading the sample made me want to purchase the book.", user_id: user_10.id)
books[8].reviews.create(rating: 2, title: "Solid by tedious", review_text: "bit heavy on needless detail that seemed added just tpnflesh out the book. But didn't do much for the actual plot.", user_id: user_11.id)
books[9].reviews.create(rating: 4, title: "Another awesome page turner.", review_text: "Great book. Lots of fun and action. Thanks for another great read!", user_id: user_12.id)
books[9].reviews.create(rating: 1, title: "HATED IT", review_text: "ONE OF THE WORST BOOKS IN MY LIFE THAT I HAVE READ!!!!!", user_id: user_13.id)
books[9].reviews.create(rating: 3, title: "Good book", review_text: "Great book! Did not want to ever leave the story.", user_id: user_14.id)
books[9].reviews.create(rating: 2, title: "Weird", review_text: "Not great. I think thats mostly because its not possible to care about any of the characters. But this book is trying something interesring. Im not sure it works.", user_id: user_15.id)
books[9].reviews.create(rating: 5, title: "Fantastic fast paced action and read.", review_text: "Another great thriller that leaves you turning the pages to find out next suspense in store for you.", user_id: user_16.id)
books[9].reviews.create(rating: 5, title: "There aren't enough stars in the sky for my rating", review_text: "I am completely speechleless. I don't even know how to begin to write this review. All I can say is this is GOLD, am I right or am I right?", user_id: user_17.id)
books[10].reviews.create(rating: 4, title: "So twisted", review_text: "Amazing", user_id: user_18.id)
books[10].reviews.create(rating: 3, title: "Enjoyable", review_text: "Not as good. Not as creepy or as twisted, but I have to admit, it held my interest in a different way.", user_id: user_19.id)
books[10].reviews.create(rating: 4, title: "Good book", review_text: "Exciting, fast paced, thriller with interesting flawed characters. Nice disclaimer at the end about the technique used in the story to cause a plane crash.", user_id: user_20.id)
books[10].reviews.create(rating: 4, title: "Good story", review_text: "Hard to put down", user_id: user_21.id)
books[10].reviews.create(rating: 3, title: "Not a great literary work", review_text: "still a nice read for an evening off when you don't feel like taking on anything too serious. The story is built up quite nicely and draws you in from the start; the ending is quite surprising.", user_id: user_22.id)
books[10].reviews.create(rating: 1, title: "This is my one and only review", review_text: "I thought the characters were incredibly shallow; one dimensional, and not one elicited any empathy and/or sympathy on my part.", user_id: user_1.id)
books[11].reviews.create(rating: 5, title: "Always a thrilling story", review_text: "There is no end to the depths the author will go to affirm his knowledge of all the aspects of the tale.", user_id: user_2.id)
books[11].reviews.create(rating: 3, title: "Pretty easy read.", review_text: "The plot develops nicely and resolves really quick.", user_id: user_3.id)
books[11].reviews.create(rating: 4, title: "Quite a thriller!", review_text: "Complex plot, amazing twists & turns with lots of surprises!", user_id: user_4.id)
books[11].reviews.create(rating: 5, title: "A great read", review_text: "A non stop thriller worthy of your time.", user_id: user_5.id)
books[11].reviews.create(rating: 4, title: "Could't put it down!", review_text: "Excellent read. Good characters.", user_id: user_6.id)
books[11].reviews.create(rating: 3, title: "Excellent Book! Five star", review_text: "One of the author's best books. Was captivating and a real page turner, could not put the book down.", user_id: user_7.id)
books[12].reviews.create(rating: 1, title: "Story too slow", review_text: "Got bored before i was halfway through. Didnt finish it", user_id: user_8.id)
books[12].reviews.create(rating: 3, title: "Maybe", review_text: "Maybe a good movie...too much going on, too many characters, unrealistic action", user_id: user_9.id)
books[12].reviews.create(rating: 4, title: "All I Can Say is Wow!", review_text: "The plot twists and winds and you just keep trying to figure out who did what. I really enjoyed it.", user_id: user_10.id)
books[12].reviews.create(rating: 5, title: "Spectacular", review_text: "A riveting story with a plot that kept changing directions", user_id: user_11.id)
books[12].reviews.create(rating: 4, title: "Great Book", review_text: "Well written, suspenseful book. Keeps you involved, can't wait to see what twists and turns the writer will take you down next. Wello worth the read.", user_id: user_12.id)
books[12].reviews.create(rating: 3, title: "Suspenseful", review_text: "I must admit keeping all the characters straight got to be a challenging, ad the main characters were a little too fantastic", user_id: user_13.id)
books[13].reviews.create(rating: 4, title: "Wonderful", review_text: "I recommend this book to everyone!", user_id: user_14.id)
books[13].reviews.create(rating: 5, title: "Great", review_text: "This is a fantastic book!! I couldn't put it down. I can't wait to read the rest of his books.", user_id: user_15.id)
books[13].reviews.create(rating: 3, title: "Fine", review_text: "Took a while to get through it. Little repetitive in the middle.", user_id: user_16.id)
books[13].reviews.create(rating: 2, title: "Forgettable", review_text: "Forgettable and predictable", user_id: user_17.id)
books[13].reviews.create(rating: 3, title: "Entertaining. A worthy read", review_text: "While a decent read, the plot was a little over the top at times.", user_id: user_18.id)
books[13].reviews.create(rating: 5, title: "WOW", review_text: "This is simply the best book I have ever read. I got in bed last night and read until dawn (not kidding) as I could not put it down. The constant plot twists and suspense leave you literally trying to figure it out until the last 10 to 20 pages.", user_id: user_19.id)
books[14].reviews.create(rating: 3, title: "Good story", review_text: "I gave it only 3 stars because what started to be a good book got ridiculous, unbelievable and predictable about 2/3 the way through.", user_id: user_20.id)
books[14].reviews.create(rating: 4, title: "Terrific", review_text: "Very well written and in a manner that you don't want to put the book down. Great read!", user_id: user_21.id)
books[14].reviews.create(rating: 3, title: "Entertaining", review_text: "Another great book featuring great characters, page turning suspense!", user_id: user_22.id)
books[14].reviews.create(rating: 1, title: "Strong start, weak middle and end", review_text: "This is the first book that I have read by this author. Ultimately, the plot is not believable.", user_id: user_1.id)
books[14].reviews.create(rating: 4, title: "Awesome story", review_text: "Kept my mind whirling and wanting more. Thank you", user_id: user_2.id)
books[14].reviews.create(rating: 3, title: "Decent", review_text: "Little too many bodies but as usual good fast paced story line that keeps you reading", user_id: user_3.id)
books[15].reviews.create(rating: 4, title: "Great book", review_text: "No spoiler here, keeps you thinking and keeps your interest.", user_id: user_4.id)
books[15].reviews.create(rating: 2, title: "Nah", review_text: "This book is too lengthy, characters overdone,main character is impossible, egotistical, dominating,and overpowering.", user_id: user_15.id)
books[15].reviews.create(rating: 2, title: "Not a winner", review_text: "I listened to this as a book on tape and the only reason I kept listening was that it was the only thing I had in the car. Thrillers need not be realistic but they do need to be believable.", user_id: user_6.id)
books[15].reviews.create(rating: 5, title: "Great read", review_text: "I got hooked almost from the first page. I brought this book along on s trip and had a hard time putting it down to go sightseeing.", user_id: user_7.id)
books[15].reviews.create(rating: 4, title: "Enjoyable read", review_text: "Exciting, fast moving, and thought provoking.", user_id: user_8.id)
books[15].reviews.create(rating: 3, title: "Not a fan", review_text: "The rating says it all....'okay, but not great.'", user_id: user_9.id)
books[16].reviews.create(rating: 2, title: "Predictable", review_text: "Very precictable and reads like a movie. But still an enjoyable read if you are looking for some fluff.", user_id: user_10.id)
books[16].reviews.create(rating: 4, title: "Two thumbs up", review_text: "I took this book with me on my holiday for a week, when i went skiing. I read the whole book that week! I loved it, such a page turner!", user_id: user_11.id)
books[16].reviews.create(rating: 4, title: "Just great", review_text: "I hate romance novels, but I love stories that include some relationships. This book is great. I could not put it down.", user_id: user_12.id)
books[16].reviews.create(rating: 3, title: "Fast paced read", review_text: "Good read. A little predictable, but all-in-all, a hard-to-put- down thriller.", user_id: user_13.id)
books[16].reviews.create(rating: 5, title: "The best", review_text: "Best book I have ever read!! Why isnt a movie?", user_id: user_14.id)
books[16].reviews.create(rating: 5, title: "Worth Losing Sleep Over", review_text: "I started reading this book the 1st time on my way to Houston for Christmas. The next night started it at sun down and didn't stop until the sun had come back up. It is very easy to get lost in the story line.", user_id: user_15.id)
books[17].reviews.create(rating: 4, title: "Great", review_text: "This was a really wonderful and exciting book. It starts out a little slow but do not give up.", user_id: user_16.id)
books[17].reviews.create(rating: 4, title: "Great book from beginning to end", review_text: "I enjoyed the characters & the suspense from beginning to end. Well done sir! Well done!", user_id: user_17.id)
books[17].reviews.create(rating: 5, title: "Great read", review_text: "One of the best reads in quite some time. Highly recommended..", user_id: user_18.id)
books[17].reviews.create(rating: 4, title: "Amazing!", review_text: "This is my very favorite book. I enjoyed getting lost in the plot.", user_id: user_19.id)
books[17].reviews.create(rating: 1, title: "Way below expectations", review_text: "Cartoonish plot and characters. Too many inconsistencies in details to mention here.", user_id: user_20.id)
books[17].reviews.create(rating: 4, title: "Recommended", review_text: "After a bit of a long beginning introduction to all players with a bit too much detailed descriptions it turned into a magnetic book I didn't want to stop reading.", user_id: user_21.id)
books[18].reviews.create(rating: 5, title: "Great book!", review_text: "I highly recommend this book. It was a true thriller and the characters were interesting as I routed for them and hoped they would prevail against the evil and uncertainty that haunted them throughout.", user_id: user_22.id)
books[18].reviews.create(rating: 3, title: "Not my favorite", review_text: "This book is almost like the author is trying too hard", user_id: user_1.id)
books[18].reviews.create(rating: 4, title: "Awesome", review_text: "I really enjoyed this book. It was exciting from the very begining", user_id: user_2.id)
books[18].reviews.create(rating: 2, title: "meh.", review_text: "A real let down from this author. Wonder if he reads these reviews?", user_id: user_3.id)
books[18].reviews.create(rating: 1, title: "No Stars for this one", review_text: "I couldn't post without a star. I couldn't finish the first 1/3 rd of the book before I just quit.", user_id: user_4.id)
books[18].reviews.create(rating: 5, title: "Love", review_text: "I love this book and im only 1 3rd through of the book", user_id: user_5.id)
books[19].reviews.create(rating: 1, title: "What a disappointment!", review_text: "I struggled through it thinking at any page the characters would wake up from a nightmare; but it did not happen.", user_id: user_6.id)
books[19].reviews.create(rating: 2, title: "Dislike", review_text: "Why is it that nobody writes a book with an ending anymore", user_id: user_7.id)
books[19].reviews.create(rating: 4, title: "Great book", review_text: "A refreshing change from a very creative writer.", user_id: user_8.id)
books[19].reviews.create(rating: 4, title: "Super", review_text: "Really good book can't what for the next one", user_id: user_9.id)
books[19].reviews.create(rating: 2, title: "Save your money", review_text: "I didn't think anyone could write a book so childish and dumb", user_id: user_10.id)
books[20].reviews.create(rating: 5, title: "BESTBOOK IN DA HISTORY OF EVER", review_text: "The author brought so much insight to the book but I would only recommend it for people with overactive imaginations.", user_id: user_11.id)
books[20].reviews.create(rating: 4, title: "Waffles", review_text: "A bit confusing for me in the beginning, but amazing for everything else.", user_id: user_12.id)
books[20].reviews.create(rating: 2, title: "So so disappointed", review_text: "I read three pages,this is a waste of my time and money", user_id: user_13.id)
books[20].reviews.create(rating: 4, title: "Don't give up", review_text: "When at first, i was super bored with the slowness. I mean i have read a great deal of boring books, but many had never gotten quite as great as this book was.", user_id: user_14.id)
books[20].reviews.create(rating: 3, title: "Pretty good", review_text: "This was a really good book. The only bad part about it was the the author made up so many words that were unfamiliar and that made it less enjoyable.", user_id: user_15.id)
books[20].reviews.create(rating: 1, title: "Terrible", review_text: "If I could give it less than one star I would...", user_id: user_16.id)
